apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-mongo-pacman-sgck
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-mongo-pacman-sgck
    app.kubernetes.io/part-of: mongo-pacman-1
  name: frontend-mongo-pacman-sgck
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: frontend-mongo-pacman-sgck
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: frontend-mongo-pacman-sgck
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
        image: pacman
        imagePullPolicy: Always
        name: front-end
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
      - image: quay.io/redhat-user-workloads-stage/ysubrama-tenant/mongo-pacman/mongodb@sha256:656b38905313877ff8d1df694a0f4a6a66f77fd94a3ec128fc608dc3ddba5129
        imagePullPolicy: Always
        name: mongo-image
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
status: {}
